name: Update last.updated
on:
  push:
    branches:
      - main
      - master
jobs:
  update-last-updated-file:
    name: "Updates the last.updated file with the current date"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'platformsh-templates' && github.event.commits[0].author.name != 'GitHub Action' }}
    steps:
      - name: 'get repo'
        id: prepautopr
        uses: actions/checkout@v3
        with:
          token: ${{secrets.TEMPLATES_GITHUB_TOKEN }}
      - name: 'set git config'
        shell: bash
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: 'update last.updated'
        id: last-updated
        shell: bash
        run: |
          date > ./.platform/last.updated
          git add ./.platform/last.updated
          git commit -m "auto-updates version, post merge"
          git push origin ${{ github.event.repository.default_branch }}

